name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:3.5
        ports:
          - 7575:7474
          - 7687:7687
        env:
          NEO4J_AUTH: none

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install SQLite3
      run: sudo apt-get install libsqlite3-dev --fix-missing
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Install gems
      run: bundle install --jobs 4 --retry 3
    - name: Setup Neo4j
      run: |
        curl -i --user neo4j:neo4j http://localhost:7575
        RAILS_ENV=test bin/rails neo4j:migrate --trace
    - name: Run tests
      run: bin/rails test
